### ISSUE TITLE
[FEATURE] Sorted alphabetically skills on characted sheet (after localization)

### ISSUE THREAD

**Issue by anclywen** [WoD5E-Developers/wod5e#37] opened 2024-07-22 14:26 UTC
In the Polish version of the Vampire character card, the skills are sorted alphabetically, e.g. "Broń biała" (eng. "Melee") is in first place. 
![image](https://github.com/user-attachments/assets/fa0015e3-7990-4a3d-8780-76e64044cd97)

In the module, the skills are sorted alphabetically in the English version, but after translation, their place does not change, which makes it very difficult to find them when playing in Polish e.g. the first is "Wysportowanie" (eng. Athletics)

![image](https://github.com/user-attachments/assets/d9066481-ae2b-40bc-a1b2-8edff21be386)

I would like the skills to be sorted alphabetically after translation, I understand that the order may differ in different language versions. If it was always sorted, the English version would be unchanged, but the translated version would be in the correct order.

Sorting skills alphabetically helps you find them quickly, now it's tough for me because I have to scan all skills to find a specific one

I don't know how difficult it is, but I can try to make changes and propose a pull request

**Comment by gbursson** [comment] 2024-08-28 13:10
I understand the premise, but I am so used to the order on the sheet that it would actually be super confusing.

**Comment by Veilza** [comment] 2024-08-28 13:50
> I understand the premise, but I am so used to the order on the sheet that it would actually be super confusing.

While I *similarly* understand *this* premise, "a bug being around for so long that users get used to it" isn't a valid reason for not fixing a bug.

In addition, I have no way to promise that the skills/attributes will always show in this order, it's just listed under the vague hope that the way they're written in the file never changes, which it absolutely can through data migrations and the like. That's definitely not ideal, and the goal is to allow alphabetical sorting throughout the sheets to maintain per-localized consistency in the future.

**Comment by gbursson** [comment] 2024-08-28 15:22
Would that be changed generally, for all localizations?

Also, how difficult (if feasible at all) would it be to have the user preference option to sort / not sort?

**Comment by Veilza** [comment] 2024-08-28 15:25
> Would that be changed generally, for all localizations?
> 
> Also, how difficult (if feasible at all) would it be to have the user preference option to sort / not sort?

The intention on the World of Darkness character sheets appears to be that they're all sorted alphabetically based on the language the character sheet is in - so yes, it would be changed for all languages.

Feasible to have an option to disable sorting, definitely. I'll probably do that. But again, this is with the big asterisk that there is **zero** guarantee that the original sorting will be saved - I'm honestly surprised that this has never been an issue in the past, but it doesn't mean that it won't be an issue in the future.

**Comment by gbursson** [comment] 2024-08-28 16:42
I guess original order would be English one.

**Comment by Veilza** [comment] 2024-08-28 16:46
> I guess original order would be English one.

The problem is that "original order"  is "the way that the skills and attributes were ordered in the original actor file." That's what I mean when I say - there's zero guarantee that the original positions of the skills and attributes will be saved, because they never were.

Hence, without vastly over-complicating things, the only options when I push this feature will be "sort alphabetically" and "don't sort alphabetically." There won't be a "Sort alphabetically based on another language."

**Comment by Veilza** [comment] 2024-09-01 03:49
Complete - Will be released with Prerelease 2 (Or stable release version 5.0.0)

**Closed by Veilza** 2024-09-01 03:49 UTC
Labels: Enhancement / Upgrade, Localization
